# Don't run CI for this config yet. We're not ready to move official builds on to Azure Pipelines
trigger: none

# Run PR validation on all branches
pr:
  branches:
    include:
    - '*'

jobs:
- template: jobs/default-build.yml
  parameters:
    jobName: Windows_Build
    jobDisplayName: "Build and test: Windows"
    agentOs: Windows
    beforeBuild:
    - powershell: "& ./src/servers/iis/tools/UpdateIISExpressCertificate.ps1"
      displayName: Setup IISExpress test certificates
- template: jobs/iisintegration-job.yml
  parameters:
    variables:
      _FolderName: IISIntegration
